# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, path: "vagrant/provision.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "1"
    vb.memory = "1024"

    # override setting in ubuntu/xenial64 box to disable output log file
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
end
